// Generated by build.py - do not edit by hand.
const VERSION='549867829e2b';
const SHELL='shell-'+VERSION;
const MEDIA='media-'+VERSION;
const CORE=['index.html','chest.html','chest-coverage.html','chest-leaders.html','chest-staffing.html','chest-happyhour.html','chest-tips.html','chest-invites.html','chest-info.html','theme.css','pages.css','poppins-latin-300-normal.woff2','poppins-latin-300-italic.woff2','poppins-latin-400-normal.woff2','poppins-latin-400-italic.woff2','poppins-latin-500-normal.woff2','poppins-latin-600-normal.woff2','poppins-latin-700-normal.woff2','manifest.webmanifest','icon-192.png','icon-512.png','icon-maskable-512.png','apple-touch-icon.png','favicon.png'];

self.addEventListener('install',function(e){
  e.waitUntil(caches.open(SHELL).then(function(c){return c.addAll(CORE);})
    .then(function(){return self.skipWaiting();}));});

self.addEventListener('activate',function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.map(function(k){
      if(k!==SHELL&&k!==MEDIA)return caches.delete(k);}));
  }).then(function(){return self.clients.claim();}));});

self.addEventListener('fetch',function(e){
  var req=e.request;
  if(req.method!=='GET')return;                       // never touch sync POSTs
  var url=new URL(req.url);
  if(url.hostname==='script.google.com')return;       // sync endpoint is live-only

  if(req.mode==='navigate'||(url.origin===location.origin&&url.pathname.endsWith('.html'))){
    // network-first so a redeploy lands, cache fallback so the booth still works offline
    e.respondWith(fetch(req).then(function(res){
      var copy=res.clone();caches.open(SHELL).then(function(c){c.put(req,copy);});return res;
    }).catch(function(){return caches.match(req).then(function(m){
      return m||caches.match('chest.html');});}));
    return;}

  if(url.origin===location.origin&&/\.(css|js|json|webmanifest)$/i.test(url.pathname)){
    // Stylesheets and scripts change between builds, often mid-conference.
    // Cache-first left reps on the previous build until a second reload, so
    // these are network-first with a cache fallback: current when online,
    // still works in the hall when not.
    e.respondWith(fetch(req).then(function(res){
      var copy=res.clone();caches.open(SHELL).then(function(c){c.put(req,copy);});return res;
    }).catch(function(){return caches.match(req);}));
    return;}

  if(url.origin===location.origin){                    // fonts and icons - never change
    e.respondWith(caches.match(req).then(function(m){return m||fetch(req);}));
    return;}

  if(req.destination==='image'||/\.(jpg|jpeg|png|webp|gif)(\?|$)/i.test(url.pathname)){
    // physician photos live on many hospital CDNs - cache-first, opaque is fine
    e.respondWith(caches.match(req).then(function(m){
      if(m)return m;
      return fetch(req).then(function(res){
        var copy=res.clone();caches.open(MEDIA).then(function(c){c.put(req,copy);});return res;
      }).catch(function(){return new Response('',{status:504});});}));}
});
