// Generated by build.py - do not edit by hand.
const VERSION='ebf5818ca7ad';
const SHELL='shell-'+VERSION;
const MEDIA='media-'+VERSION;
const PHOTOS=['photo-chest-1.jpg','photo-chest-11.jpg','photo-chest-12.jpg','photo-chest-13.jpg','photo-chest-14.jpg','photo-chest-16.jpg','photo-chest-18.jpg','photo-chest-19.jpg','photo-chest-2.jpg','photo-chest-20.jpg','photo-chest-22.jpg','photo-chest-23.jpg','photo-chest-24.jpg','photo-chest-25.jpg','photo-chest-26.jpg','photo-chest-27.jpg','photo-chest-29.jpg','photo-chest-3.jpg','photo-chest-30.jpg','photo-chest-31.jpg','photo-chest-32.jpg','photo-chest-33.jpg','photo-chest-34.jpg','photo-chest-35.jpg','photo-chest-36.jpg','photo-chest-37.jpg','photo-chest-38.jpg','photo-chest-39.jpg','photo-chest-4.jpg','photo-chest-40.jpg','photo-chest-43.jpg','photo-chest-44.jpg','photo-chest-45.jpg','photo-chest-5.jpg','photo-chest-6.jpg','photo-chest-7.jpg'];
const CORE=['index.html','chest.html','chest-leaders.html','chest-staffing.html','chest-happyhour.html','chest-tips.html','chest-invites.html','chest-info.html','theme.css','pages.css','poppins-latin-300-normal.woff2','poppins-latin-300-italic.woff2','poppins-latin-400-normal.woff2','poppins-latin-400-italic.woff2','poppins-latin-500-normal.woff2','poppins-latin-600-normal.woff2','poppins-latin-700-normal.woff2','manifest.webmanifest','icon-192.png','icon-512.png','icon-maskable-512.png','apple-touch-icon.png','favicon.png'];

self.addEventListener('install',function(e){
  e.waitUntil(caches.open(SHELL).then(function(c){return c.addAll(CORE);})
    // Physician photos are precached one by one so a single missing file can't
    // fail the install; the booth hall has poor signal, so they must work offline.
    .then(function(){return caches.open(MEDIA);})
    .then(function(c){return Promise.all(PHOTOS.map(function(p){return c.add(p).catch(function(){});}));})
    .then(function(){return self.skipWaiting();}));});

self.addEventListener('activate',function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.map(function(k){
      if(k!==SHELL&&k!==MEDIA)return caches.delete(k);}));
  }).then(function(){return self.clients.claim();}));});

self.addEventListener('fetch',function(e){
  var req=e.request;
  if(req.method!=='GET')return;                       // never touch sync POSTs
  var url=new URL(req.url);
  if(url.hostname==='script.google.com')return;       // sync endpoint is live-only

  if(req.mode==='navigate'||(url.origin===location.origin&&url.pathname.endsWith('.html'))){
    // network-first so a redeploy lands, cache fallback so the booth still works offline
    e.respondWith(fetch(req).then(function(res){
      var copy=res.clone();caches.open(SHELL).then(function(c){c.put(req,copy);});return res;
    }).catch(function(){return caches.match(req).then(function(m){
      return m||caches.match('chest.html');});}));
    return;}

  if(url.origin===location.origin&&/\.(css|js|json|webmanifest)$/i.test(url.pathname)){
    // Stylesheets and scripts change between builds, often mid-conference.
    // Cache-first left reps on the previous build until a second reload, so
    // these are network-first with a cache fallback: current when online,
    // still works in the hall when not.
    e.respondWith(fetch(req).then(function(res){
      var copy=res.clone();caches.open(SHELL).then(function(c){c.put(req,copy);});return res;
    }).catch(function(){return caches.match(req);}));
    return;}

  if(url.origin===location.origin){                    // fonts, icons, local photos
    e.respondWith(caches.match(req).then(function(m){
      if(m)return m;
      return fetch(req).then(function(res){
        if(res.ok){var copy=res.clone();caches.open(MEDIA).then(function(c){c.put(req,copy);});}
        return res;});}));
    return;}

  if(req.destination==='image'||/\.(jpg|jpeg|png|webp|gif)(\?|$)/i.test(url.pathname)){
    // physician photos live on many hospital CDNs - cache-first, opaque is fine
    e.respondWith(caches.match(req).then(function(m){
      if(m)return m;
      return fetch(req).then(function(res){
        var copy=res.clone();caches.open(MEDIA).then(function(c){c.put(req,copy);});return res;
      }).catch(function(){return new Response('',{status:504});});}));}
});
